// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfodL6U2zyr1wFRa4vLRAQApO-p0z7vxA',
    appId: '1:796366672440:web:78820b8b54772e14c4cccd',
    messagingSenderId: '796366672440',
    projectId: 'byteshop-b015c',
    authDomain: 'byteshop-b015c.firebaseapp.com',
    storageBucket: 'byteshop-b015c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIRrLGc2pYz9FF8EedbaFt7UK4FOudKiY',
    appId: '1:796366672440:android:4f2897f16e384762c4cccd',
    messagingSenderId: '796366672440',
    projectId: 'byteshop-b015c',
    storageBucket: 'byteshop-b015c.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8UN6TCRCOu_ysoIBLwCscqNEerHhZtcY',
    appId: '1:796366672440:ios:7c0c0b6a6ed6d805c4cccd',
    messagingSenderId: '796366672440',
    projectId: 'byteshop-b015c',
    storageBucket: 'byteshop-b015c.firebasestorage.app',
    iosBundleId: 'com.example.miniCart',
  );
}
